### ISSUE TITLE
Can't find libraries with custom Boost 

### ISSUE THREAD

**Issue by thibaudk** [OSSIA/ossia-supercollider#10]
Here is the error log

-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- SuperCollider Version: 3.9.0-beta1
-- Building from branch 3.9, commit hash is 75d0e91ff
-- Compiling with Qt GUI
-- Found Pthreads: /usr/lib/x86_64-linux-gnu/libpthread.so  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Error at /home/scrime/Documents/repos/ossia-supercollider/dependencies/cmake-3.9.3-Linux-x86_64/share/cmake-3.9/Modules/FindBoost.cmake:1902 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.65.1

  Boost include path: /usr/local/include

  Could not find the following Boost libraries:

          boost_regex
          boost_test_exec_monitor

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  CMakeLists.txt:259 (find_package)

-- building boost libraries manually
You have called ADD_LIBRARY for library boost_system without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library boost_program_options without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library boost_filesystem without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library boost_thread without any source files. This typically indicates a problem with your CMakeLists.txt file

**Comment by avilleret** [comment]
what's your `cmake` invocation options ?
what's your OS ?
usually we need to define `BOOST_ROOT` with the path to boost header with something like `-DBOOST_ROOT=/path/to/boost`
see https://github.com/OSSIA/libossia/wiki/Building for more details

**Comment by avilleret** [comment]
I just run into the same issue with a non-OSSIA project after my first reply.
It seems that FindBoost.cmake need some binaries and headers are not enough.
I fixed it by installing boost library 1.65.1 from package manager (on arch).

**Comment by thibaudk** [comment]
I'm on ubuntu Studio 17.10.
i have boost library 1.65.1 installed
(./bootstrap.sh --with-libraries=atomic,date_time,chrono,exception,timer,thr
ead,system,filesystem,program_options,regex,test)

libossia seems to be building fine. Altho, the .so file is made in the
build Folder but isn't installed after sudo make install in usr/local/lib.
it is only when building supercollider that the problem with boost happens.
It persists after reinstalling the whole library.

boost_1_65_1 dosen't seem to be available from the package manager. After
adding the ppa with

sudo add-apt-repository ppa:nschloe/boost-nightly

or
sudo add-apt-repository ppa:boost-latest/ppa

the package can't be found

Err:31 http://ppa.launchpad.net/boost-latest/ppa/ubuntu artful
Release
  404  Not Found




2017-11-11 20:01 GMT+01:00 Antoine Villeret <notifications@github.com>:

**Comment by thibaudk** [comment]
Ok, so the working setup requires boost and libossia to be built localy in the ossi-Supercollider and only alow supercollider to be built localy.
This avoids the sclang mismatch, ant in only requires to manualy remove the last -DCMAKE_INSTALL_PREFIX from the script.
No further tempering seems successful so far.
