### ISSUE TITLE
OSSIA_MirrorNode causes crash

### ISSUE THREAD

**Issue by thibaudk** [OSSIA/ossia-supercollider#19]
When Instantiating an OSSIA_MirrorNode,
Supercollider freezes and eventually, the interpreter crashes.
 
OSSIA_MirrorNode seems to be completely replaceable with OSSIA_MirrorParameters tho.

Tested on Ubuntu Studio 17.10 & 18.04

**Comment by pchdev** [comment]
well, it's not if you want to set some attributes for an explicit node (and not a parameter)

**Comment by thibaudk** [comment]
Sure, it worked as a temporary workaround, but the MirrorNode works perfectly now.
Well done!
